@author:Juarez Monteiro

# Keras

### 1. A Basic Example

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

Using Theano backend.
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: Quadro M6000 (CNMeM is disabled, cuDNN 4007)


In [2]:
np.random.seed(474)

data = np.random.random((1000,100))
labels = np.random.randint(2, size=(1000,1))

In [3]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['accuracy'])

In [4]:
model.fit(data, labels, epochs=10, batch_size=32, verbose=0)
predictions = model.predict(data)
scores = model.evaluate(data, labels)
print('\n%s: %.2f%%' % (model.metrics_names[1], scores[1]*100))

  32/1000 [..............................] - ETA: 0s
acc: 62.80%


### 2. Data

In [5]:
from keras.datasets import boston_housing, mnist, cifar10, imdb
(x_train, y_train), (x_test, y_test) = mnist.load_data()
(x_train2, y_train2), (x_test2, y_test2) = boston_housing.load_data()
(x_train3, y_train3), (x_test3, y_test3) = cifar10.load_data()
(x_train4, y_train4), (x_test4, y_test4) = imdb.load_data(num_words=20000)
num_classes = 10

### 3. Preprocessing

#### 3.1 Sequence Padding

In [6]:
len(x_train4[0])
x_train4.shape

(25000,)

In [7]:
# Sequence Padding
from keras.preprocessing import sequence

x_train4 = sequence.pad_sequences(x_train4, maxlen=80)
x_test4 = sequence.pad_sequences(x_test4, maxlen=80)

In [8]:
# pad_sequences is used to ensure that all sequences in a list have the same length. 
# By default this is done by padding 0 in the beginning of each sequence until each 
# sequence has the same length as the longest sequence.

# https://stackoverflow.com/questions/42943291/what-does-keras-io-preprocessing-sequence-pad-sequences-do

len(x_train4[0])
x_train4.shape
x_train4[0]

array([   15,   256,     4,     2,     7,  3766,     5,   723,    36,
          71,    43,   530,   476,    26,   400,   317,    46,     7,
           4, 12118,  1029,    13,   104,    88,     4,   381,    15,
         297,    98,    32,  2071,    56,    26,   141,     6,   194,
        7486,    18,     4,   226,    22,    21,   134,   476,    26,
         480,     5,   144,    30,  5535,    18,    51,    36,    28,
         224,    92,    25,   104,     4,   226,    65,    16,    38,
        1334,    88,    12,    16,   283,     5,    16,  4472,   113,
         103,    32,    15,    16,  5345,    19,   178,    32], dtype=int32)

#### 3.2 One-Hot Encoding

In [9]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()
y_train.shape

(60000,)

In [10]:
from keras.utils import to_categorical

Y_train = to_categorical(y_train, num_classes)
Y_test = to_categorical(y_test, num_classes)
Y_train3 = to_categorical(y_train3, num_classes)
Y_test3 = to_categorical(y_test3, num_classes)

In [11]:
Y_train[1]

array([ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 3.3 Train and Test Sets

In [12]:
from urllib2 import urlopen
data = np.loadtxt(urlopen("http://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data"),delimiter=",")
X = data[:,0:8]
y = data [:,8]

In [13]:
from sklearn.model_selection import train_test_split

X_train5, X_test5, y_train5, y_test5 = train_test_split(X, y, test_size=0.33, random_state=42)

#### 3.4 Standardization/Normalization

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train5)
standardized_X = scaler.transform(X_train5)
standardized_X_test = scaler.transform(X_test5)

In [15]:
standardized_X[0]

array([ 1.89917664, -0.19475093,  1.55717838, -1.32537379, -0.68585955,
       -1.04293476,  1.60661512,  0.06905859])

In [16]:
X_train5[0]

array([  10.   ,  115.   ,   98.   ,    0.   ,    0.   ,   24.   ,
          1.022,   34.   ])

### 4. Model Architecture

#### 4.1 Sequential Model

In [17]:
from keras.models import Sequential

model = Sequential()
model3 = Sequential()

#### 4.2 Multi-Layer Perceptron (MLP)

#### 4.2.1 Binary Classification

In [18]:
from keras.layers import Dense

model.add(Dense(12, input_dim=8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(8, kernel_initializer='uniform', activation='relu'))
model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

#### 4.2.2 Multi-Class Classification

In [19]:
from keras.layers import Dropout

model.add(Dense(512, activation='relu', input_shape=(784,)))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10, activation='softmax'))

#### 4.3 Regression

In [20]:
model.add(Dense(64, activation='relu', input_dim=train_data.shape[1]))
model.add(Dense(1))

NameError: name 'train_data' is not defined

#### 4.4 Convolutional Neural Network (CNN)

In [21]:
(x_train,y_train),(x_test,y_test) = mnist.load_data()

In [22]:
x_train.shape

(60000, 28, 28)

In [23]:
from keras.layers import Input, Reshape
from keras.utils import np_utils

# load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# normalize inputs from 0-255 to 0-1
X_train = X_train / 255
X_test = X_test / 255

x_train = x_train.reshape(x_train.shape[0], 28, 28, 1).astype('float32')
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1).astype('float32')

y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)

num_classes = y_test.shape[1]

v = x_train.shape[1:] + (1,)

v[:3]

(28, 28, 1)

In [24]:
from keras.layers import Activation, Conv2D, MaxPooling2D, Flatten



model2 = Sequential()

model2.add(Conv2D(32, (3,3), padding='same', input_shape=v[:3]))
model2.add(Activation('relu'))
model2.add(Conv2D(32, (3,3)))
model2.add(Activation('relu'))
model2.add(MaxPooling2D(pool_size=(2,2)))
model2.add(Dropout(0.25))
model2.add(Flatten())
model2.add(Dense(512))
model2.add(Activation('relu'))
model2.add(Dropout(0.5))
model2.add(Dense(10))
model2.add(Activation('softmax'))

#### 4.4.1 Inspect Model

In [ ]:
# Model output shape
#model2.output_shape

# Model summary representation
#model2.summary()

# Model configuration
#model2.get_config()

# List all weight tensor in the model
#model2.get_weights()

#### 4.5 Model Compile

In [25]:
model2.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

#### 4.5 Model Training

In [26]:
model2.fit(x_train, y_train, batch_size=128, epochs=5, validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 17s - loss: 5.8279 - acc: 0.6070 - val_loss: 0.1004 - val_acc: 0.9700
Epoch 2/5
60000/60000 [==============================] - 17s - loss: 0.1343 - acc: 0.9633 - val_loss: 0.0617 - val_acc: 0.9801
Epoch 3/5
60000/60000 [==============================] - 17s - loss: 0.0997 - acc: 0.9730 - val_loss: 0.0918 - val_acc: 0.9763
Epoch 4/5
60000/60000 [==============================] - 17s - loss: 0.0839 - acc: 0.9766 - val_loss: 0.0655 - val_acc: 0.9828
Epoch 5/5
60000/60000 [==============================] - 17s - loss: 0.0770 - acc: 0.9785 - val_loss: 0.0572 - val_acc: 0.9854


#### 4.6 Evaluate your model's performance

In [27]:
score = model2.evaluate(x_test, y_test, batch_size=32)

 9600/10000 [===========================>..] - ETA: 0s

In [30]:
print score

[0.057211451819504149, 0.98540000000000005]


#### 4.7 Prediction

In [31]:
model2.predict(x_test, batch_size=32)

array([[  1.38283482e-12,   4.46199223e-11,   3.02837861e-08, ...,
          9.99999285e-01,   5.43523837e-10,   2.62275961e-07],
       [  6.19562832e-13,   4.14600215e-10,   1.00000000e+00, ...,
          2.75234870e-12,   4.67737349e-10,   1.95783483e-14],
       [  4.08556966e-10,   9.99999404e-01,   4.19881196e-09, ...,
          3.74552371e-08,   3.55517983e-07,   2.04187733e-09],
       ..., 
       [  6.57902931e-17,   9.50698808e-12,   6.72417241e-14, ...,
          3.30988179e-08,   3.74023621e-08,   1.76314696e-08],
       [  2.86916095e-18,   7.02447877e-19,   7.20995696e-19, ...,
          1.47704928e-15,   2.62840786e-06,   8.39506307e-13],
       [  1.00621733e-09,   8.96535775e-13,   5.49677075e-11, ...,
          1.41451602e-13,   4.85409712e-10,   1.50557657e-11]], dtype=float32)

In [32]:
model2.predict_classes(x_test, batch_size=32)

 9408/10000 [===========================>..] - ETA: 0s

array([7, 2, 1, ..., 4, 5, 6])

In [35]:
from keras.models import load_model
#model2.save('model_file.h5')

In [34]:
my_model = load_model('model_file.h5')

#### 4.8 Model Fine-tuning

In [36]:
# Optimization Parameters

from keras.optimizers import RMSprop
opt = RMSprop(lr=0.0001, decay=1e-6)

In [37]:
model2.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [38]:
model2.fit(x_train, y_train, batch_size=128, epochs=5, validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 17s - loss: 0.0443 - acc: 0.9872 - val_loss: 0.0441 - val_acc: 0.9874
Epoch 2/5
60000/60000 [==============================] - 17s - loss: 0.0402 - acc: 0.9881 - val_loss: 0.0413 - val_acc: 0.9877
Epoch 3/5
60000/60000 [==============================] - 17s - loss: 0.0382 - acc: 0.9889 - val_loss: 0.0405 - val_acc: 0.9877
Epoch 4/5
60000/60000 [==============================] - 18s - loss: 0.0359 - acc: 0.9899 - val_loss: 0.0414 - val_acc: 0.9876
Epoch 5/5
60000/60000 [==============================] - 17s - loss: 0.0361 - acc: 0.9896 - val_loss: 0.0406 - val_acc: 0.9884


In [41]:
from keras.callbacks import EarlyStopping

early_stopping_monitor = EarlyStopping(patience=2)
model2.fit(x_train, 
           y_train, 
           batch_size=128, 
           epochs=5, 
           validation_data=(x_test, y_test),
           callbacks=[early_stopping_monitor] 
          )

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 17s - loss: 0.0348 - acc: 0.9898 - val_loss: 0.0423 - val_acc: 0.9875
Epoch 2/5
60000/60000 [==============================] - 17s - loss: 0.0331 - acc: 0.9903 - val_loss: 0.0417 - val_acc: 0.9876
Epoch 3/5
60000/60000 [==============================] - 17s - loss: 0.0321 - acc: 0.9905 - val_loss: 0.0399 - val_acc: 0.9876
Epoch 4/5
60000/60000 [==============================] - 17s - loss: 0.0347 - acc: 0.9897 - val_loss: 0.0409 - val_acc: 0.9878
Epoch 5/5
60000/60000 [==============================] - 17s - loss: 0.0319 - acc: 0.9907 - val_loss: 0.0430 - val_acc: 0.9869
