# Pytorch - Tensors!


This notebook focus on the use of tensors in Pytorch. This material is the same available by Matthew Mayo in [KDnuggets](https://www.kdnuggets.com/2018/05/pytorch-tensor-basics.html).


**@notebook_author: [Juarez Monteiro](https://jrzmnt.github.io).**

---

*This is an introduction to PyTorch's Tensor class, which is reasonably analogous to Numpy's ndarray, and which forms the basis for building neural networks in PyTorch.*

[**PyTorch**](https://pytorch.org/) has made an impressive dent on the machine learning scene since Facebook open-sourced it in early 2017. 
It may not have the widespread adoption that TensorFlow has -- which was initially released well over a year prior, enjoys the backing of Google, and had the luxury of establishing itself as the gold standard as a new wave of neural networking tools was being ushered in -- but the attention that PyTorch receives in the research community especially is quite real. 
Much of this attention comes both from its relationship to Torch proper, and its dynamic computation graph.

![img](https://www.kdnuggets.com/wp-content/uploads/tensor-examples.jpg "Example of tensors.")

As excited as I have recently been by turning my own attention to PyTorch, this is **not** really a **PyTorch tutorial**; it's more of an **introduction to PyTorch's Tensor class**, which is reasonably analogous to Numpy's ndarray.m

## Tensor (Very) Basics

So let's take a look at some of PyTorch's tensor basics, starting with creating a tensor (using the **Tensor class**):

In [20]:
import torch

# Create a Torch tensor
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

#### You can transpose a tensor in one of 2 ways:

In [7]:
# Transpose
t.t()

# Transpose (via permute)
t.permute(-1,0)

tensor([[ 1.,  4.],
        [ 2.,  5.],
        [ 3.,  6.]])

#### Note that neither result in a change to the original.

In [9]:
t

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])

#### Reshape a tensor with view:

In [23]:
# Reshape via view
#t = t.view(3,2)
t.view(3,2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.]])

In [26]:
# Just another example
t.view(6,1)

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.]])

*It should be obvious that mathematical conventions which are followed by **Numpy** carry over to **PyTorch Tensors** (specifically I'm referring to row and column notation).*

#### Create a tensor and fill it with zeros (you can accomplish something similar with ones()):

In [33]:
t = torch.zeros(3,3)
t

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]])

#### Create a tensor with randoms pulled from the normal distribution:

In [36]:
t = torch.randn(3,3)
t

tensor([[ 0.5573,  1.4828,  0.7756],
        [ 0.2646, -0.6887,  0.7479],
        [ 1.7068, -0.4491, -0.0172]])

#### Shape, dimensions, and datatype of a tensor object:

In [37]:
# Some tensor info
print('Tensor shape:', t.shape)   # t.size() gives the same
print('Number of dimensions:', t.dim())
print('Tensor type:', t.type())   # there are other types

('Tensor shape:', torch.Size([3, 3]))
('Number of dimensions:', 2)
('Tensor type:', 'torch.FloatTensor')


It should also be obvious that, beyond mathematical concepts, a number of programmatic and instantiation similarities between ndarray and Tensor implementations exist.

You can **slice PyTorch tensors** the same way you **slice ndarrays**, which should be familiar to anyone who uses other Python structures:

In [44]:
# Slicing
t = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print t

# Every row, only the last column
print(t[:, -1])

# First 2 rows, all columns
print(t[:2, :])

# Lower right most corner
print(t[-1:, -1:])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])
tensor([ 3.,  6.,  9.])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])
tensor([[ 9.]])


### PyTorch Tensor To and From Numpy ndarray

You can easily create a tensors from an ndarray and vice versa. These operations are fast, since the data of both structures will share the same memory space, and so no copying is involved. This is obviously an efficient approach.

In [49]:
import numpy as np

In [50]:
# ndarray to tensor
a = np.random.randn(3, 5)
t = torch.from_numpy(a)
print(a)
print(t)
print(type(a))
print(type(t))

[[-1.19342516 -2.20770196  0.05667432 -0.07387365 -0.25733323]
 [-2.4731455  -0.21433011  1.61143989 -1.6815513  -1.85775728]
 [-0.27608511  1.20422478 -0.15524044 -2.03573287  0.21608626]]
tensor([[-1.1934, -2.2077,  0.0567, -0.0739, -0.2573],
        [-2.4731, -0.2143,  1.6114, -1.6816, -1.8578],
        [-0.2761,  1.2042, -0.1552, -2.0357,  0.2161]], dtype=torch.float64)
<type 'numpy.ndarray'>
<class 'torch.Tensor'>


In [51]:
# tensor to ndarray
t = torch.randn(3, 5)
a = t.numpy()
print(t)
print(a)
print(type(t))
print(type(a))

tensor([[-1.7276, -0.1433,  0.9729,  0.0480, -1.1742],
        [ 1.3700,  0.2172,  0.2750,  0.4016, -1.0471],
        [ 0.8151,  0.1270, -1.8187, -0.6939,  0.8868]])
[[-1.7276318  -0.1433103   0.97291845  0.04797237 -1.1742376 ]
 [ 1.3699548   0.21723264  0.27496466  0.40157077 -1.0470865 ]
 [ 0.81514406  0.12698859 -1.8186685  -0.6939064   0.886809  ]]
<class 'torch.Tensor'>
<type 'numpy.ndarray'>


### Basic Tensor Operations

Here are a **few tensor operations**, which you can compare with Numpy implementations for fun. First up is the **cross product**:

In [63]:
# Compute cross product
t1 = torch.randn(4,3)
t2 = torch.randn(4,3)
print t1
print t2
print t1.cross(t2)

tensor([[ 0.7481, -1.1264, -1.0862],
        [ 0.3520, -0.9261, -1.0435],
        [-0.0773, -1.0966, -0.8887],
        [-0.5405, -1.2386,  0.9814]])
tensor([[ 2.2663,  0.3275,  1.5255],
        [-0.1170,  0.7240, -2.1284],
        [-2.1810, -0.0520, -0.9417],
        [ 0.0301, -1.1192, -0.1893]])
tensor([[-1.3626, -3.6029,  2.7977],
        [ 2.7266,  0.8712,  0.1465],
        [ 0.9865,  1.8655, -2.3877],
        [ 1.3328, -0.0728,  0.6422]])
