# #3 Linear Algebra

## Identity and Inverse Matrices


This notebook and the others from this series focus on review important concepts of Linear Algebra, such knowledge are very important to understand further Deep Learning concepts.
This material is the same available By Hadrien Jean in [KDnuggets](https://www.kdnuggets.com/2018/05/boost-data-science-skills-learn-linear-algebra.html).


*This content is also part of a series following the chapter 2 on linear algebra from the Deep Learning Book by Goodfellow, I., Bengio, Y., and Courville, A.*


**@notebook_author: [Juarez Monteiro](https://jrzmnt.github.io).**

---

# Identity Matrices

The identity matrix $\boldsymbol{I}_n$ is a special matrix of shape $(n \times n)$ that is filled with 0 except the diagonal that is filled with 1.

<img src="https://hadrienj.github.io/assets/images/2.3/identity-matrix.png" width="200px" height="200px" />

An identity matrix can be created with the Numpy function eye():

```python
numpy.eye()
```


In [1]:
import numpy as np

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

When 'apply' the identity matrix to a vector the result is this same vector: $$\boldsymbol{I}_n \space\boldsymbol{x}=\boldsymbol{x}$$

We can see an example bellow:

$$
\begin{bmatrix}
    1 & 0 & 0 \\\\
    0 & 1 & 0 \\\\
    0 & 0 & 1 
\end{bmatrix}
\times
\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    x_3
\end{bmatrix}
=
\begin{bmatrix}
    1 \times x_1 & 0 \times x_2 & 0 \times x_3 \\\\
    0 \times x_1 & 1 \times x_2 & 0 \times x_3 \\\\
    0 \times x_1 & 0 \times x_2 & 1 \times x_3 
\end{bmatrix}
=
\begin{bmatrix}
    x_1 \\\\
    x_2 \\\\
    x_3 \\
\end{bmatrix}
$$

In [3]:
x = np.array([[2],[6],[3]])
x

array([[2],
       [6],
       [3]])

In [9]:
xid = np.eye(x.shape[0]).dot(x)
xid

array([[2.],
       [6.],
       [3.]])

## Intuition

You can think of a matrix as a way to transform objects in a n-dimensional space. It applies a linear transformation of the space. We can say that we apply a matrix to an element: this means that we do the dot product between this matrix and the element. We will see this notion thoroughly in the next chapters but the identity matrix is a good first example. It is a particular example because the space doesn’t change when we apply the identity matrix to it.

We saw that $\boldsymbol{x}$ was not altered after being multiplied by $\boldsymbol{I}$.

> ### *The space doesn’t change when we apply the identity matrix to it.*

## Inverse Matrices

The matrix inverse of $\boldsymbol{A}$ is denoted $\boldsymbol{A}^{-1}$.
It is the matrix that results in the identity matrix when it is multiplied by $\boldsymbol{A}$:

$$\boldsymbol{A}^{-1}\boldsymbol{A}=\boldsymbol{I}_n$$

This means that if we apply a linear transformation to the space with $\boldsymbol{A}$, it is possible to go back with $\boldsymbol{A}^{-1}$.
It provides a way to cancel the transformation.

*E.g.:*
$$
A=
\begin{bmatrix}
    3 & 0 & 2 \\\\
    2 & 0 & -2 \\\\
    0 & 1 & 1 
\end{bmatrix}
$$

For this example, we will use the Numpy function ```linalg.inv()``` to calculate the inverse of $\boldsymbol{A}$.
Let's start by creating $\boldsymbol{A}$:

In [15]:
A = np.array([[3,0,2], [2,0,-2], [0,1,1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

Now we calculte its inverse:

In [17]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])