# #1 Linear Algebra

## Scalars, Vectors, Matrices and Tensors


This notebook and the others from this series focus on review important concepts of Linear Algebra, such knowledge are very important to understand further Deep Learning concepts.
This material is the same available By Hadrien Jean in [KDnuggets](https://www.kdnuggets.com/2018/05/boost-data-science-skills-learn-linear-algebra.html).


*This content is also part of a series following the chapter 2 on linear algebra from the Deep Learning Book by Goodfellow, I., Bengio, Y., and Courville, A.*


**@notebook_author: [Juarez Monteiro](https://jrzmnt.github.io).**

---

## Let’s start with some basic definitions:

<!--![img](https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png "Difference between a scalar, a vector, a matrix and a tensor.")-->

<img src="https://hadrienj.github.io/assets/images/2.1/scalar-vector-matrix-tensor.png" width="800px" height="800px" />

- A **scalar** is a single number
- A **vector** is an array of numbers
- A **matrix** is a 2-D array
- A **tensor** is a n-dimensional array with n > 2
    
**We will follow the conventions used in the Deep Learning Book:**

- Scalars are written in lowercase and italics. For instance: *n*
- Vectors are written in lowercase, italics and bold type. For instance: ***x***
- Matrices are written in uppercase, italics and bold. For instance: ***X***


## Create a vector with Python and Numpy

In [6]:
import numpy as np

In [7]:
# We will start by creating a vector. This is just a 1-dimensional array:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

## Create a (3x2) matrix with nested brackets

In [10]:
# The array() function can also create 2-dimensional arrays with nested brackets:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

## Shape

The shape of an array (that is to say its dimensions) tells you the number of values for each dimension. For a 2-dimensional array it will give you the number of rows and the number of columns. Let’s find the shape of our preceding 2-dimensional array A. Since A is a Numpy array (it was created with the array() function) you can access its shape with:

In [22]:
print "Matrix's A shape:", A.shape
print "Vector's x shape:", x.shape

Matrix's A shape: (3, 2)
Vector's x shape: (4,)


We can see that ***A*** has **3 rows** and **2 columns**. <br>
However, the vector ***x*** has only **one dimension**.

## Transposition

With transposition you can convert a row vector to a column vector and vice versa.


![img_transposition](https://hadrienj.github.io/assets/images/2.1/vector-transposition.png "Vector transposition.")

<center> The transpose ***A***<sup>T</sup> of the matrix ***A*** corresponds to the mirrored axes. If the matrix is a square matrix (same number of columns and rows):</center> 

<!--![img_matrix_transposition](https://hadrienj.github.io/assets/images/2.1/square-matrix-transposition.png "Square matrix transposition.")-->

<img src="https://hadrienj.github.io/assets/images/2.1/square-matrix-transposition.png" width="400px" height="800px" />

 <center>If the matrix **is not square** the idea is the same:</center>

<!--![img_non_square_matrix_transposition](https://hadrienj.github.io/assets/images/2.1/non-squared-matrix-transposition.png "Non-square matrix transposition.")-->

<img src="https://hadrienj.github.io/assets/images/2.1/non-squared-matrix-transposition.png" width="400px" height="800px" />



<center>It is important to note that the **shape** (***m***x***n***) is inverted and becomes (***n***x***m***).</center>

<!---![img_matrix_transposition_notation](https://hadrienj.github.io/assets/images/2.1/dimensions-transposition-matrix.png "Dimension of matrix transposition.")-->

<img src="https://hadrienj.github.io/assets/images/2.1/dimensions-transposition-matrix.png" width="400px" height="800px" />

## Create a matrix A and transpose it

In [40]:
A = np.array([[1, 2], [3, 4], [5, 6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
A_t = A.T
A_t

array([[1, 3, 5],
       [2, 4, 6]])

We can see that the number of columns becomes the number of rows with transposition and vice versa.

In [42]:
print A.shape
print A_t.shape

(3, 2)
(2, 3)


## Addition

<img src=https://hadrienj.github.io/assets/images/2.1/matrix-addition.png height="200px" width="400px"/>

Matrices can be added if they have the same shape: ***A*** + ***B*** = ***C***

Each cell of ***A*** is added to the corresponding cell of ***B***: 

***A***<sub>*ij*</sub> + ***B***<sub>*ij*</sub> = ***C***<sub>*ij*</sub>

*i is the row index and j the column index.*

## Create two matrices A and B and add them

In numpy you can add matrices jus as you would add vectors or scalars.

In [47]:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
B = np.array([[2,5], [7,4], [4,3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [50]:
# Add matrices A and B
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

## Add a scalar to a matrix

It is also possible to add a scalar to a matrix. This means adding this scalar to each cell of the matrix.

In [52]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
# Adding a escalar to the matrix A

escalar = 4
C = A + escalar
C

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Broadcasting

Numpy can handle operations on arrays of different shapes. The smaller array will be extended to match the shape of the bigger one. The advantage is that this is done in C under the hood (like any vectorized operations in Numpy). Actually, we used broadcasting in the example **above**. The scalar was converted in an array of same shape as ***A***.

### Add two matrices of different shapes

In [59]:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
B = np.array([[2], [4], [6]])
B

array([[2],
       [4],
       [6]])

In [61]:
# Broadcasting
C = A + B
C

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

## References

- [Original Source](https://hadrienj.github.io/posts/Deep-Learning-Book-Series-2.1-Scalars-Vectors-Matrices-and-Tensors/)
- [Broadcasting in Numpy](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)
- [Discussion on Arrays and matrices](https://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u)
- [Math is fun - Matrix introduction](https://www.mathsisfun.com/algebra/matrix-introduction.html)