# #2.1 Linear Algebra

## Multiplying Matrices and Vectors


This notebook and the others from this series focus on review important concepts of Linear Algebra, such knowledge are very important to understand further Deep Learning concepts.
This material is the same available By Hadrien Jean in [KDnuggets](https://www.kdnuggets.com/2018/05/boost-data-science-skills-learn-linear-algebra.html).


*This content is also part of a series following the chapter 2 on linear algebra from the Deep Learning Book by Goodfellow, I., Bengio, Y., and Courville, A.*


**@notebook_author: [Juarez Monteiro](https://jrzmnt.github.io).**

---

## Introduction

We will see some very important concepts in this chapter. The dot product is used in every equation explaining data science algorithms so it’s worth the effort to understand it. Then we will see some properties of this operation. Finally, we will get some intuition on the link between matrices and systems of linear equations.

## Multiplying Matrices and Vectors

The standard way to multiply matrices is not to multiply each element of one with each element of the other (this is the element-wise product) but to calculate the sum of the products between rows and columns. The matrix product, also called dot product, is calculated as following:

<img src="https://hadrienj.github.io/assets/images/2.2/dot-product.png" width="400px" height="400px" />

The number of columns of the first matrix must be equal to the number of rows of the second matrix. Thus, if the dimensions, or the shape of the first matrix, is (*m* x *n*) the second matrix need to be of shape (*n* x *x*). The resulting matrix will have the shape (*m* x *x*).

## With Numpy

The Numpy function ``` dot() ``` can be used to compute the matrix product (or dot product). Let’s try to reproduce some example. 
As a starter we will see the multiplication of a **matrix** and a **vector**.

***A*** x ***b*** = ***C***

In [10]:
import numpy as np

In [11]:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [16]:
C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

We can see in this example that the **shape** of ***A*** is **(3x2)** and the shape of ***b*** is **(2x1)**. So the dimensions of ***C*** are **(3×1)**.

Multiplication of **two matrices**.

***A*** x ***B*** = ***C***

In [18]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
B = np.array([[2,7],[1,2],[3,6]])
B

array([[2, 7],
       [1, 2],
       [3, 6]])

In [20]:
C = A.dot(B)
C

array([[ 13,  29],
       [ 31,  74],
       [ 49, 119],
       [ 67, 164]])

In [31]:
print "A:%s x B:%s = C:%s" % (A.shape, B.shape, C.shape)


A:(4, 3) x B:(3, 2) = C:(4, 2)


## Properties of the dot product

We will now see some interesting properties of the matrix multiplication. It will become useful as we move forward. Using simple examples for each property will provide a way to check them while we get used to the Numpy functions.

## Matrices mutliplication is distributive

***A*** (***B*** + ***C***) = ***AB*** + ***AC***

In [38]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [39]:
B = np.array([[5], [2]])
B

array([[5],
       [2]])

In [40]:
C = np.array([[4], [3]])
C

array([[4],
       [3]])

***A*** (***B*** + ***C***):

In [45]:
D = A.dot(B+C)
D

array([[33],
       [29],
       [93]])

Is equivalent to ***AB***+***AC***:

In [49]:
D = A.dot(B) + A.dot(C)
D

array([[33],
       [29],
       [93]])

## Matrices mutliplication is associative

***A*** (***BC***) = (***AB***) ***C***

In [50]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A

array([[2, 3],
       [1, 4],
       [7, 6]])

In [51]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

In [54]:
C = np.array([[4], [3]])
C

array([[4],
       [3]])

***A***(***BC***):

In [55]:
D = A.dot(B.dot(C))
D

array([[100],
       [ 85],
       [287]])

Is equivalent to (***AB***) ***C***:

In [58]:
D = A.dot(B).dot(C)
D

array([[100],
       [ 85],
       [287]])

## Matrix multiplication is not commutative

***AB*** != ***BA***

In [59]:
A = np.array([[2,3],[6,5]])
A

array([[2, 3],
       [6, 5]])

In [60]:
B = np.array([[5,3],[2,2]])
B

array([[5, 3],
       [2, 2]])

***AB:***

In [63]:
AB = np.dot(A,B)
AB

array([[16, 12],
       [40, 28]])

***BA:***

In [64]:
BA = np.dot(B,A)
BA

array([[28, 30],
       [16, 16]])

## However vector multiplication is commutative

***x***<sup>T</sup>***y*** = ***y***<sup>T</sup>***x***

In [68]:
x = np.array([[2],[6]])
x

array([[2],
       [6]])

In [71]:
y = np.array([[5],[2]])
y

array([[5],
       [2]])

***x***<sup>T</sup>***y*** :

In [74]:
xt_y = x.T.dot(y)
xt_y

array([[22]])

***y***<sup>T</sup>***x*** :

In [75]:
yt_x = y.T.dot(x)
yt_x

array([[22]])

## Simplification of the matrix product

(***AB***)<sup>T</sup> = ***B***<sup>T</sup> ***A***<sup>T</sup>

In [78]:
A = np.array([[2, 3], [1, 4], [7, 6]])
A 

array([[2, 3],
       [1, 4],
       [7, 6]])

In [79]:
B = np.array([[5, 3], [2, 2]])
B

array([[5, 3],
       [2, 2]])

(***AB***)<sup>T</sup>

In [82]:
AB_t = A.dot(B).T
AB_t

array([[16, 13, 47],
       [12, 11, 33]])

is equivalent to ***B***<sup>T</sup>***A***<sup>T</sup> :

In [84]:
Bt_At = B.T.dot(A.T)
Bt_At

array([[16, 13, 47],
       [12, 11, 33]])